framework:
  messenger:
    default_bus: messenger.bus.default

    transports:
      # sync transport: direct uitvoeren, geen queue/database
      sync: 'sync://'

    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: sync

    buses:
      messenger.bus.default: []
